name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on the name of your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Set Git identity
        run: |
          git config --global user.email "245809@edu.p.lodz.pl"
          git config --global user.name "SzymonGieraga"

      - name: Deploy to GitHub Pages
        run: |
          ./node_modules/.bin/gh-pages -d build -u "SzymonGieraga <245809@edu.p.lodz.pl>" -t $GH_PAGES_TOKEN
